# Generated by Django 4.2.27 on 2026-06-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ats_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='application',
            name='ats_semantic_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='ats_skill_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='manual_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='recruiter_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='review_status',
            field=models.CharField(choices=[('not_reviewed', 'Chưa xem'), ('consider', 'Cần cân nhắc'), ('fit', 'Phù hợp'), ('rejected', 'Từ chối')], default='not_reviewed', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cvdocument',
            name='education_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cvdocument',
            name='extracted_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='cvdocument',
            name='extracted_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='cvdocument',
            name='extracted_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='cvdocument',
            name='extracted_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cvdocument',
            name='project_summary',
            field=models.TextField(blank=True),
        ),
    ]
