# Generated by Django 4.2.27 on 2026-06-02 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_application_ai_summary_application_ats_breakdown_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-last_event_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='notification',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='notification',
            name='group_key',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='notification',
            name='last_event_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notification',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('application_success', 'Ứng tuyển thành công'), ('application_status', 'Cập nhật ứng tuyển'), ('new_application', 'Đơn ứng tuyển mới')], max_length=40),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
