# Generated by Django 4.2.27 on 2026-06-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_skill_skillalias_skillalias_unique_skill_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvdocument',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cvdocument',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
