# Generated by Django 4.2.27 on 2026-06-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_cvdocument_deleted_at_cvdocument_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvdocument',
            name='certification_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cvdocument',
            name='experience_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cvdocument',
            name='parsed_sections',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='cvdocument',
            name='skill_evidence',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
